name: Build and Release

on:
  workflow_dispatch: # Permite rodar o botão manualmente no site!
  push:
    tags:
      - 'v*' # Aciona quando você criar uma tag que comece com 'v', como v2.0.0

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: 📦 Checando o repositório
        uses: actions/checkout@v4

      - name: 📦 Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📥 Instalando Dependências do Vite e Electron
        working-directory: './interface electron'
        run: npm install

      - name: 🔨 Compilando o Frontend (Vite)
        working-directory: './interface electron'
        run: npm run build

      - name: 🚀 Empacotando e Publicando no GitHub Releases (.exe)
        working-directory: './interface electron'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win --publish always
